### ISSUE TITLE
Add the google-oauth2 connection to the new_tenant.js recipe

### ISSUE THREAD

**Issue by twistedstream** [auth0-extensions/auth0-reset-tenant#1]
The current [`new_tenant.js` recipe](https://github.com/twistedstream/auth0-tenant-reset/blob/master/recipes/new_tenant.js) properly creates a `Default App` client and a `Username-Password-Authentication` connection, but it should also enable the Google social connection in order to replicate what you get by default when you create a new tenant.

**Comment by rrexford** [comment]
on it.

**Comment by rrexford** [comment]
still working on it don't fire me!
