### ISSUE TITLE
Would it be possible to run the auth0-reset-tenant similar to management dashboard? 

### ISSUE THREAD

**Issue by saltukalakus** [auth0-extensions/auth0-reset-tenant#13]
Could it be possible to run auth0-reset-tenant as a first class API consumer. Each different demo environment can have a auth0-reset-tenant app link with demo specific recipe as a query parameter which would be self sufficient to setup dashboard for the demo.

**Comment by twistedstream** [comment]
We essentially need a way for Auth0 via a link to automatically install an extension (i.e. the future "Reset Tenant" extension), and load a specific recipe. At least that's how it would have to work if this was being done as an extension.
