### ISSUE TITLE
Silent execution of the external recipe with a command line option.

### ISSUE THREAD

**Issue by saltukalakus** [auth0-extensions/auth0-reset-tenant#18]
For example, if you want to just run the passed in external receipt, maybe you'd pass the --quiet (or -q) switch:

```bash
reset-tenant -q my-recipe.js
```

And maybe if you wanted to silently run other builtin recipes:

```bash
reset-tenant -q --recipe clear,new_tenant
```

**Comment by twistedstream** [comment]
Given the state of the command now, I think we should use a subcommand line `run`:

```bash
reset-tenant run --recipe clear [custom-receipt.js]
```

where:
* `--recipe` (`-r`): the one or more builtin recipes (by ID) to run (eg. `clear` or `clear,new_tenant`)
* `[custom-receipt.js]`: optionally run a custom recipe script _after_ the builtin recipes

We may also need to support a list subcommand so the user can see the list of builtin recipes by their IDs:

```bash
reset-tenant ls
```
```
[clear] Clear: Removes all entities from the tenant (including webtasks/extensions) and puts settings back to their defaults
[new_tenant] New Tenant: Creates all the elements in a new Auth0 Tenant
...
```

> Recipe IDs are simply the file names of the recipe scripts in the [/src/recipes/builtin](/src/recipes/builtin) directory, minus their `.js` file extension
