### ISSUE TITLE
Search for a DSL library for recipes.

### ISSUE THREAD

**Issue by saltukalakus** [auth0-extensions/auth0-reset-tenant#21]
* Should help us write declarative recipes, leaving how it is made to internal libraries.
* Should support asynchronous flows. 
* Should be callable from Javascript.

**Comment by twistedstream** [comment]
Also could support inline JS if the DSL itself wasn't expressive enough

**Comment by twistedstream** [comment]
One idea that @saltukalakus had was to use CoffeeScript. It would be a lower level DSL, but still easier to author recipes than with JS. We will continue to research other possibilities or perhaps something that sits on top of CoffeeScript.

**Comment by saltukalakus** [comment]
Adds some more control on parallel, serial operations with extending CoffeScript. Might be interesting => http://maxtaco.github.io/coffee-script/

**Comment by twistedstream** [comment]
@saltukalakus: IcedCoffeeScript looks cool. The `await` and `defer` keywords make the async control flow very easy to read. Lets keep this under heavy consideration.

**Comment by twistedstream** [comment]
@saltukalakus: After a little more review, I'm having some concerns about IcedCoffeeScript. Looks like it hasn't been updated in a while and I'm seeing rumors online that's not going to be an active project anymore. 

CoffeeScript proper on the other hand seems to still be going strong. I'm thinking if we introduced some helper methods into our API that made concurrency flow control easier to express, especially in CoffeeScript, I think we'd be in good shape. And lets use as much of standard libraries as possible. For example, if we have a `context` argument with the recipe `run` function and we add some helper functions like `context.parallel` or `context.series`, we could make sure `context.parallel` just wraps something common like `Promise.all`.

**Comment by saltukalakus** [comment]
I guess as we decided to use CoffeScript and custom libraries to simply the recipes we can close this issue.
