### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by twistedstream** [auth0-extensions/auth0-reset-tenant#24]
Given the reach of this tool, it might make sense to give it a different name than "reset tenant". Besides not all recipes are intended to reset the tenant completely back to a known state. Others are simply additive to what currently exists in the tenant.

**Comment by saltukalakus** [comment]
Some alternatives I can think of;

auth0- {manage/dashboard}-{builder/installer/creator}
auth0-{build/install/create}-{manage/dashboard}

**Comment by twistedstream** [comment]
I'm thinking something more generic that doesn't identity necessary a particular part of the Auth0 platform. Like auth0-automator but more cool.

Auth0-chef is a possibility but it's already referring to an existing tool (although we do use the term recipe)

**Comment by twistedstream** [comment]
Idea: auth0-wizard and we use the term "spell" instead of "recipe"

**Comment by saltukalakus** [comment]
Cool combination "auth0-wizard" with "spell". Makes sense.

**Comment by twistedstream** [comment]
@saltukalakus: which do you like better:

* auth0-wizard
* auth0-mage

**Comment by saltukalakus** [comment]
I would prefer auth0-wizard.

**Comment by twistedstream** [comment]
@saltukalakus: I like it too
@sgmeyer: thoughts?
