### ISSUE TITLE
error: 'Too Many Requests'

### ISSUE THREAD

**Issue by l8nite** [auth0-extensions/auth0-reset-tenant#31]
When attempting to run reset-tenant with a pretty vanilla/boring setup:

```
ERROR: [Error: Unsuccessful response attempting to reset custom login page: status=429, body=
{ statusCode: 429,
  error: 'Too Many Requests',
  message: 'Global limit has been reached',
  errorCode: 'too_many_requests' }]
Error: Unsuccessful response attempting to reset custom login page: status=429, body=
{ statusCode: 429,
  error: 'Too Many Requests',
  message: 'Global limit has been reached',
  errorCode: 'too_many_requests' }
```

Let me know if any other detail is helpful

Edit: From https://auth0.com/docs/policies/rate-limits
> For scripts and rules that call Auth0 APIs, you should always handle rate limiting by checking the X-RateLimit-Remaining header and acting appropriately when the number returned nears 0. You should also add logic to handle cases in which you exceed the provided rate limits and receive the HTTP Status Code 429 (Too Many Requests); in this case, if a re-try is needed, it is best to allow for a back-off to avoid going into an infinite re-try loop.

**Comment by l8nite** [comment]
It's still relevant, it would be nice to see some API rate limiting in the client.

**Comment by Fredericson** [comment]
Any news on this? I have exactly the same issue.

**Comment by saltukalakus** [comment]
This project doesn't have active development. Instead you may use [deploy cli tool](https://auth0.com/docs/extensions/deploy-cli) for the same purpose. 

I have tested the command line option of deploy cli in a free tenant and it worked without issues.

Install the tool a0deploy:
npm i -g auth0-deploy-cli

Get a snapshot of the state you would like to preserve:
a0deploy export -c config.json -f yaml -o ./

Update the tenant with the stored state:
a0deploy import -c config.json -f yaml -i ./tenant.yaml

Here is my config.json file, client ID and client secrets are for my [machine to machine](https://auth0.com/docs/api/management/v2/create-m2m-app) app for the management API. I have excluded the client name of this app to be overwritten in the config file.
{
  "AUTH0_DOMAIN": "saltuk-01-19.auth0.com",
  "AUTH0_CLIENT_ID": "ocHGhIzO2SYZRLbG6O0S6pSg8Q97uyIB",
  "AUTH0_CLIENT_SECRET": "redacted",
  "AUTH0_ALLOW_DELETE": true,
  "AUTH0_EXCLUDED_CLIENTS":["API Explorer Application"]
}
